INSERT INTO groups (name, curator_name)
VALUES ('3МОАИС', 'Петров Александр Сергеевич'),
       ('2ПМ', 'Смирнова Елена Владимировна'),
       ('2МОАИС', 'Козлов Дмитрий Иванович'),
       ('3ПМ', 'Волкова Мария Петровна'),
       ('1М', 'Николаев Андрей Викторович'),
       ('2М', 'Орлова Светлана Дмитриевна'),
       ('3ИВТ ТИИ', 'Громов Илья Сергеевич');

INSERT INTO users (name, age, email, role, group_id)
VALUES ('Иван Петров', 20, 'ivan.petrov@mail.ru', 'student', 1),
       ('Мария Сидорова', 21, 'maria.sidorova@gmail.com', 'student', 1),
       ('Алексей Козлов', 19, 'alex.kozlov@yandex.ru', 'student', 1),
       ('Елена Волкова', 22, 'elena.volkova@mail.ru', 'student', 2),
       ('Дмитрий Смирнов', 20, 'dmitry.smirnov@gmail.com', 'student', 2),
       ('Анна Попова', 21, 'anna.popova@yandex.ru', 'student', 3),
       ('Сергей Иванов', 23, 'sergey.ivanov@mail.ru', 'student', 3),
       ('Ольга Новикова', 22, 'olga.novikova@gmail.com', 'student', 3),
       ('Артем Васильев', 24, 'artem.vasilev@mail.ru', 'student', 3),
       ('Наталья Кузнецова', 21, 'natalia.kuznetsova@gmail.com', 'student', 3),
       ('Павел Михайлов', 22, 'pavel.mikhailov@yandex.ru', 'student', 4),
       ('Ирина Соколова', 20, 'irina.sokolova@mail.ru', 'student', 4),
       ('Александр Петров', 45, 'alexander.petrov@university.ru', 'teacher', NULL),
       ('Елена Смирнова', 38, 'elena.smirnova@university.ru', 'teacher', NULL),
       ('Дмитрий Козлов', 42, 'dmitry.kozlov@university.ru', 'teacher', NULL),
       ('Мария Волкова', 35, 'maria.volkova@university.ru', 'teacher', NULL),
       ('Андрей Николаев', 50, 'andrey.nikolaev@university.ru', 'administrator', NULL),
       ('Светлана Орлова', 48, 'svetlana.orlova@university.ru', 'administrator', NULL),
       ('Владимир Громов', 20, 'vladimir.gromov@mail.ru', 'student', 5),
       ('Екатерина Белова', 21, 'ekaterina.belova@gmail.com', 'student', 6),
       ('Сергей Лебедев', 22, 'sergey.lebedev@yandex.ru', 'student', 6),
       ('Ольга Крылова', 23, 'olga.krylova@mail.ru', 'student', 7);

INSERT INTO events (title, description, event_time, location, max_participants)
VALUES ('Конференция по IT', 'Ежегодная конференция для IT-специалистов', '2025-02-15 10:00:00',
        'Москва, ул. Тверская, 25', 100),
       ('Воркшоп по веб-разработке', 'Практический воркшоп по современной веб-разработке', '2025-02-20 14:30:00',
        'Санкт-Петербург, Невский пр., 45', 30),
       ('Митап Data Science', 'Встреча специалистов по анализу данных', '2026-03-05 18:00:00',
        'Москва, Пресненская наб., 8', 50),
       ('Мастер-класс по дизайну', 'Интенсив по UI/UX дизайну для начинающих', '2026-02-25 11:00:00',
        'Казань, ул. Баумана, 35', 25),
       ('Хакатон Startup Weekend', '48-часовой марафон по созданию стартапов', '2026-03-10 09:00:00',
        'Новосибирск, ул. Ленина, 12', NULL),
       ('Лекция по искусственному интеллекту', 'Обзор современных тенденций в AI и машинном обучении',
        '2026-02-28 19:00:00', 'Екатеринбург, пр. Ленина, 51', 200);

INSERT INTO event_registrations (user_id, event_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 1),
       (2, 4),
       (3, 1),
       (3, 5),
       (4, 1),
       (4, 3),
       (4, 6),
       (5, 1),
       (6, 1),
       (6, 3),
       (6, 5),
       (7, 1),
       (8, 1),
       (9, 1),
       (10, 1),
       (11, 1),
       (12, 1);